version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: goldsun_mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Pass123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourStrong@Pass123' -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10

  init-db:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ./goldsunDB.sql:/init.sql
    entrypoint: >
      /bin/sh -c "
        sleep 10 &&
        /opt/mssql-tools/bin/sqlcmd -S goldsun_mssql -U sa -P 'YourStrong@Pass123' -i /init.sql
      "

  server:
    build: ./server
    container_name: goldsun_server
    depends_on:
      mssql:
        condition: service_healthy
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    command: ["node", "app.js"]

  client:
    build: ./client
    container_name: goldsun_client
    ports:
      - "5173:5173"
    depends_on:
      - server

  admin:
    build: ./admin-app
    container_name: goldsun_admin
    ports:
      - "5174:5174"
    depends_on:
      - server

networks:
  default:
    name: goldsun-app_default
